package com.salesianostriana.rest.controllers;

public class NewPersonWithIdException extends RuntimeException {
	
	public NewPersonWithIdException() {
		super("The ids are generated by the database");
	}

}
